version: "3.9"
services:
  portfolio:
    image: ghcr.io/${GHCR_NAMESPACE:-owner}/${GHCR_REPO:-portfolio}:${TAG:-latest}
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # env_file:
    #   - .env
